name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  generate-docker-image:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Buildx
          uses: docker/setup-buildx-action@v2

        - uses: actions-ecosystem/action-get-latest-tag@v1
          id: get-latest-tag

        - name: Print latest tag
          run: echo ${{ steps.get-latest-tag.outputs.tag }}

        - name: Log in to GHCR
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Compute lowercase repository (owner/repo)
          id: repo
          run: |
            # GitHub provides GITHUB_REPOSITORY as OWNER/REPO; convert to lowercase for Docker tags
            # Use bash parameter expansion to lowercase without introducing extra quotes
            echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

        - name: Build and push tagged Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            tags: ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.get-latest-tag.outputs.tag }}

        - name: Build and push latest Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64
            tags: ghcr.io/${{ steps.repo.outputs.repo }}:latest